# Alacritty Configuration
import = [
  "~/.config/alacritty/themes/tokyo-nights-storm.toml",
  "~/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-la"]

[window]
dimensions = { columns = 121, lines = 30 }
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.95
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
option_as_alt = "Both"

[scrolling]
history = 10001
multiplier = 4

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }
size = 22.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = "Underline"
blink_interval = 751
unfocused_hollow = true
thickness = 1.15
