[keyboard]
bindings = [
  # iTerm-like tmux bindings
  { key = "D", mods = "Command", chars = "\u0001\u007c" },       # Split vertically
  { key = "D", mods = "Command|Shift", chars = "\u0001\u005f" }, # Split horizontally
  { key = "W", mods = "Command", chars = "\u0001x" },            # Close pane
  { key = "T", mods = "Command", chars = "\u0001c" },            # New window
  { key = "S", mods = "Command", chars = "\u0001s" },            # List sessions
  { key = "Left", mods = "Command", chars = "\u0001\u001b[D" },  # Select pane on the left
  { key = "Right", mods = "Command", chars = "\u0001\u001b[C" }, # Select pane on the right
  { key = "Up", mods = "Command", chars = "\u0001\u001b[A" },    # Select pane above
  { key = "Down", mods = "Command", chars = "\u0001\u001b[B" },  # Select pane below
  { key = "Z", mods = "Command", chars = "\u0001z" },            # Toggle pane zoom
]
